### ISSUE TITLE
install.ps1 fails to install the module

### ISSUE THREAD

**Issue by canix1** [miriamxyra/EventList#1]
Missing reference to repository in URL for downloading EventList

1. Download install.ps1
2. Run install.ps1
4. See error:
Downloading repository from 'https://github.com/<InsertUsernameHere>/EventList/archive/master.zip'
Installation of the module EventList failed!

Solution:
Update row 40 in install.ps1 to:
$BaseUrl = "https://github.com/miriamxyra/EventList"

**Comment by FriedrichWeinmann** [comment]
PR is pending (it hadn't been updated from the template)

**Comment by miriamxyra** [comment]
Thanks for reviewing, PR is merged
